name: streamlit-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pillow
  - scikit-learn
  - pyyaml
  - cmake
  - dlib
  - face_recognition
  - pytorch
  - torchvision
  - pip
  - pip:
    - streamlit
    - matplotlib